### ISSUE TITLE
section-main-product.css - PostCSS compiling error.

### ISSUE THREAD

**Issue by zacariec** [Shopify/dawn#1306]
---
name: Bug issue
about: Use this template for reporting a bug
labels: 'type:bug'

---

**Describe the current behavior**
PostCSS errors on line 643 of `section-main-product.css`

Error line:
`border-radius: var(--media-radius) - var(--media-border-width);`

In style rule: `.product__media-toggle:focus-visible:after`

```
ParserError: Syntax Error at line: 1, column 21
    at */**/section-main-product.css:643:3
    at Parser.error (*/**/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (*/**/node_modules/postcss-values-parser/lib/parser.js:183:18)
    at Parser.parseTokens (*/**/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (*/**/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (*/**/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse */**/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at */**/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at */**/node_modules/postcss/lib/container.js:72:18
    at */**/node_modules/postcss/lib/container.js:55:18
    at Rule.each (*/**/node_modules/postcss/lib/container.js:41:16)
    at processResult (*/**/node_modules/webpack/lib/NormalModule.js:701:19)
    at */**/node_modules/webpack/lib/NormalModule.js:807:5
    at */**/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at */**/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (*/**/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (*/**/node_modules/postcss-loader/dist/index.js:96:7)
```
**Describe the expected behavior**
Should parse without error

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 3.0.0
- PostCSS ^8.3.5

**Possible solution**
Encapsulating the border radius-style with calc(), passes without error.
`border-radius: calc(var(--media-radius) - var(--media-border-width));`

**Comment by lukechadwick** [comment]
Also experiencing this, the rest of the file uses calc() so ideally this line will follow the same pattern.

This rule can probably be removed altogether since overridden by the rule just below it on line 665:
https://github.com/Shopify/dawn/blob/3549f96c19bdb0789440b0f4019b562b69e9393a/assets/section-main-product.css#L666
![image](https://user-images.githubusercontent.com/6725655/164351432-a7c4b849-5865-4980-9301-f9d15ad24b29.png)
