### ISSUE TITLE
trekkie.ts:37 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'uniqToken')

### ISSUE THREAD

**Issue by ascheucher-shopify-partner** [Shopify/dawn#3359]
## Describe the current behavior
Loading a page with Dawn theme, throws an error:

```
trekkie.ts:37 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'uniqToken')
    at trekkie.ts:37:28
    at Array.reduce (<anonymous>)
    at trekkie.ts:36:21
    at Generator.next (<anonymous>)
    at r (tslib.es6.mjs:118:56)
```

## Describe the expected behavior
No error message thrown.

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 13.0.1
- Chrome Version 122.0.6261.129
- macOS Version 14.2.1 (23C71)

## Possible solution
No suggestion.

**Comment by ascheucher-shopify-partner** [comment]
To whomever this happens to, you are very likely running the shop based in the European Union and you don't have an app installed handling cookies & GDPR.

After installing an app and giving consent, the stack trace disappeared.

Not a very gentle way to tell one needs to handle the issue.
