### ISSUE TITLE
Shopify Subscription App error on Dawn theme 15.0.2

### ISSUE THREAD

**Issue by drewlonious** [Shopify/dawn#3588]
## Describe the current behavior
on load... 
`app-embed-block.js:320 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at updatePriceAndSellingPlanInfo (app-embed-block.js:320:44)
    at HTMLDocument.<anonymous> (app-embed-block.js:3:3)`

`function updatePriceAndSellingPlanInfo() {
  const productInfo = document.querySelector(
    '#shopify-section-product-template',
  );

  const activePurchaseOption = productInfo.querySelector(
    '.shopify_subscriptions_app_block:not(.shopify_subscriptions_app_block--hidden)',
  );`

when selecting different subscription plan options
`
app-embed-block.js:164 Uncaught TypeError: Cannot set properties of null (setting 'checked')
    at app-embed-block.js:164:21
    at Array.forEach (<anonymous>)
    at selectSellingPlanAndGroupRadios (app-embed-block.js:163:17)
    at handleRadioButtonChange (app-embed-block.js:137:5)
    at HTMLInputElement.<anonymous> (app-embed-block.js:12:7)
`
![Screenshot 2024-08-15 at 2 14 53 PM](https://github.com/user-attachments/assets/5e10b151-e788-4292-b301-9c8468055941)

## Describe the expected behavior
It shouldn't be throwing errors when null

## Version information (Dawn, browsers and operating systems)

- Dawn Version: 15.0.2
- Chrome Version 27.0.6533.100 (Official Build) (arm64)
- macOS Version 14.5

## Additional context/screenshots

on load
![Screenshot 2024-08-15 at 2 16 04 PM](https://github.com/user-attachments/assets/d011ece6-50bb-4745-866b-ee48186039d1)

on selling plan change
![Uploading Screenshot 2024-08-15 at 2.16.31 PM.png…]()

**Comment by IlyaZha** [comment]
I have same error
