### ISSUE TITLE
Running 'shopify populate' does not work

### ISSUE THREAD

**Issue by GuillermoCasanova** [Shopify/dawn#403]
**Describe the current behavior**
Attempting to run the command "shopify populate" does not work and leads to an error in the console.

**Describe the expected behavior**
Instead of populate the store with products it errors in the console. Below is the error: 
```

This command ran with ID: 42495
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:74:in `block in request': 404 (ShopifyCli::API::APIRequestNotFoundError)
{"errors":"Not Found"}
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:86:in `request'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/api.rb:36:in `query'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:136:in `block in fetch_api_version'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:143:in `fetch_api_version'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:117:in `api_client'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:42:in `block in query'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api.rb:43:in `query'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/schema.rb:10:in `get'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:113:in `schema'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:102:in `input_options'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:33:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/admin_api/populate_resource_command.rb:17:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/command.rb:19:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/executor.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/bin/shopify:33:in `block in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /usr/local/Cellar/shopify-cli/2.1.0/gems/shopify-cli-2.1.0/bin/shopify:32:in `<top (required)>'
        from /usr/local/bin/shopify:6:in `load'
        from /usr/local/bin/shopify:6:in `<main>'
```

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.1.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Comment by PaulNewton** [comment]
@GuillermoCasanova this is the dawn project the theme, are you have a problem with the shopify-app **cli program**?
Try here [https://github.com/Shopify/shopify-app-cli](https://github.com/Shopify/shopify-app-cli)

**Comment by GuillermoCasanova** [comment]
Ah thanks @PaulNewton !
